# Site settings
baseurl = "localhost:1313"
themesDir = "themes"
publishDir = "docs"
languageCode = "en-us"
title = "My Personal Website"
theme = "cactus"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-118754978-1"
# Disable comments by leaving disqusShortname empty
disqusShortname = "mrrudrud"

[params]
	name = "MrRudRud"
	description = "Describe your website"
	bio = "Blogger & Programmer"
	# Enter optionally your twitter account
	twitter = "Your Twitter account"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I'm a fullstack developer enthusiast"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    # twitter  = "https://www.twitter.com/"
    facebook = "https://www.facebook.com/mrrudrud"
    github   = "https://github.com/MrRudRud"
    # dribble  = "https://www.dribbble.com/"
